name: fordev
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.1.2
  equatable: ^2.0.5
  get: ^4.6.6
  flutter_secure_storage: ^9.2.2
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  test: ^1.24.9
  mocktail: ^1.0.4
  faker: ^2.1.0

flutter:

  uses-material-design: true
  assets:
    - lib/ui/assets/

flutter_icons:
  ios: true
  android: true
  image_path_android: lib/ui/assets/icon/android.png
  image_path_ios: lib/ui/assets/icon/ios.png
  adaptive_icon_background: lib/ui/assets/icon/background.png
  adaptive_icon_foreground: lib/ui/assets/icon/foreground.png
